-- table: kontoendring

create table kontoendring
(
    aktor_id integer,
    personidenter varchar(255),
    mottatt timestamp without time zone,
    status varchar(20),
    statustidspunkt timestamp without time zone,
    id integer not null generated by default as identity ( increment 1 start 1000000 minvalue 1 maxvalue 2147483647 cache 1 ),
    constraint kontoendring_pkey primary key (id),
    constraint fk_aktor foreign key (aktor_id)
        references aktor (id) match simple
        on update no action
        on delete no action
)

tablespace pg_default;

create index index_kontoendring_fk_aktor on kontoendring(aktor_id)

/*** rulle tilbake ***

  drop table kontoendring
  delete from flyway_schema_history where version = '1.0.9';

 */