-- Table: hendelsearkiv

-- DROP TABLE hendelsearkiv;

CREATE TABLE hendelsearkiv
(
    hendelseid varchar(255),
    opplysningstype varchar(255),
    endringstype varchar(255),
    master varchar(255),
    offset_pdl integer,
    personidenter varchar(255),
    tidligere_hendelseid varchar(255),
    hendelse varchar(255),
    opprettet timestamp without time zone,
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1000000 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    CONSTRAINT hendelsearkiv_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;