-- Table: kontoendring

CREATE TABLE kontoendring
(
    aktorid varchar(255),
    mottatt timestamp without time zone,
    publisert timestamp without time zone,
    status varchar(20),
    statustidspunkt timestamp without time zone,
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1000000 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    CONSTRAINT kontoendring_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

CREATE INDEX INDEX_KONTOENDRING_KONTOEIER ON KONTOENDRING(AKTORID)

/*** Rulle tilbake ***

  DROP TABLE kontoendring
  delete from flyway_schema_history where version = '1.0.4';

 */