-- Table: hendelsemottak

-- DROP TABLE hendelsemottak;

CREATE TABLE hendelsemottak
(
    hendelseid varchar(255),
    opplysningstype varchar(255),
    endringstype varchar(255),
    personidenter varchar(255),
    tidligere_hendelseid varchar(255),
    hendelse varchar(5000),
    master varchar(255),
    offset_pdl integer,
    status varchar(20),
    statustidspunkt timestamp without time zone,
    opprettet timestamp without time zone,
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1000000 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    CONSTRAINT hendelsemottak_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;