--- table: aktor

create table aktor
(
    aktorid varchar(13),
    publisert timestamp without time zone,
    id integer not null generated by default as identity ( increment 1 start 1000000 minvalue 1 maxvalue 2147483647 cache 1 ),
    constraint aktor_pkey primary key (id)
)

tablespace pg_default;

create index index_aktor_aktorid on aktor(aktorid)

/*** rulle tilbake ***

  drop table aktor;
  delete from flyway_schema_history where version = '1.0.4';

 */