alter table hendelsemottak
    alter column id
        add generated by default as identity ( increment 1 start 1000000 minvalue 1 maxvalue 2147483647 cache 1 ),
    add constraint fk_aktor foreign key (aktor_id)
        references aktor (id) match simple
        on update no action
        on delete no action,
    add constraint hendelsemottak_pkey primary key (id);

create index index_hendelsemottak_aktor_id on hendelsemottak(aktor_id);

/*** Rulle tilbake **

  alter table hendelsemottak
    drop constraint fk_aktor,
    drop constraint hendelsemottak_pkey;
  drop index index_hendelsemottak_aktor_id;
  delete from flyway_schema_history where version = '1.0.7';

 */

